const opponents={
  desi:{label:"Desi Steelers",summary:"A balanced side with a strong central core and a recognized goalkeeper.",threats:["Rishabh","Vamshi","Nasiq"],instructions:["One midfielder closes the ball while the other blocks the pass into Rishabh or Nasiq.","Keep both defenders behind the ball when we attack; do not give Vamshi an open transition.","Move the ball quickly across the pitch and make their central players defend side to side."],marking:"Chirag controls the central threat. DJ or Varun tracks the quickest runner.",duties:{leftMid:"Close the ball",rightMid:"Cover central pass",leftDef:"Support pressure",rightDef:"Protect the goal",striker:"Stay available"},footnote:"Roles mirror when the ball switches sides. The far-side midfielder always tucks inside."},
  muggles:{label:"Muggles FC",summary:"Their deepest technical group can create through several different players.",threats:["Vishnu","Dhruv","Dheeraj","Ashu"],instructions:["Keep midfield close to defense so they cannot play through the center.","Force possession toward the sideline, then press with the touchline as an extra defender.","Keep Nuhu or Varun available as the counter outlet instead of bringing everyone behind the ball."],marking:"Use zonal coverage first. DJ follows a fast runner only after Chirag calls the switch.",duties:{leftMid:"Screen passes",rightMid:"Screen passes",leftDef:"Hold the line",rightDef:"Hold the line",striker:"Counter outlet"},footnote:"Stay patient. Their strongest advantage appears when our midfield and defense become separated."},
  scouts:{label:"Scouts FC",summary:"Pradnyal is the main all-around threat, supported by Kartik and Sagar SJ.",threats:["Pradnyal","Kartik","Sagar SJ"],instructions:["Stagger the midfield: one player pressures Pradnyal and the other screens the central lane.","Do not send two players directly at Pradnyal; that releases another attacker into space.","Make their lower-cost players build the attack and press immediately after a poor first touch."],marking:"DJ or Varun stays goal-side of Pradnyal; Chirag covers rather than joining the same challenge.",duties:{leftMid:"Press receiver",rightMid:"Screen center",leftDef:"Cover channel",rightDef:"Cover channel",striker:"Counter outlet"},footnote:"The screening role follows the central passing lane rather than staying on a fixed side."}
};
const shapes={
  balanced:{tab:"Balanced",label:"BASE SHAPE",title:"2–2–1 · Balanced",mentality:"BALANCED",note:"Our default shape: two defenders, two connected midfielders, and one forward outlet.",players:[
    {key:"gk",role:"GOALKEEPER",name:"Minti",duty:"Organize · simple pass",x:50,y:90,className:"goalkeeper"},
    {key:"leftDef",role:"LEFT DEFENDER",name:"DJ / Shailesh",duty:"Hold position",x:28,y:70},
    {key:"rightDef",role:"RIGHT DEF / CDM",name:"Chirag",duty:"Lead the line",x:72,y:70},
    {key:"leftMid",role:"LEFT MID",name:"Prajna / Sangram",duty:"Close the ball",x:29,y:43},
    {key:"rightMid",role:"RIGHT MID",name:"Varun",duty:"Cover inside",x:71,y:43},
    {key:"striker",role:"FORWARD",name:"Nuhu / Vivek",duty:"Passing outlet",x:50,y:17}
  ]},
  protect:{tab:"Protect lead",label:"GAME MANAGEMENT",title:"3–2 · Protect a lead",mentality:"COMPACT",note:"Close the center, defend the width of the goal, and always leave one safe outlet.",players:[
    {key:"gk",role:"GOALKEEPER",name:"Minti",duty:"Slow and organize",x:50,y:90,className:"goalkeeper"},
    {key:"leftDef",role:"LEFT DEFENDER",name:"Shailesh / Rajeev",duty:"Close wide",x:22,y:69},
    {key:"centerDef",role:"CENTER BACK",name:"Chirag",duty:"Cover behind",x:50,y:69},
    {key:"rightDef",role:"RIGHT DEFENDER",name:"DJ",duty:"Close wide",x:78,y:69},
    {key:"leftOutlet",role:"LEFT OUTLET",name:"Prajna / Sangram",duty:"Link midfield",x:33,y:33},
    {key:"rightOutlet",role:"RIGHT OUTLET",name:"Nuhu / Varun",duty:"Stay available",x:67,y:33}
  ]},
  chase:{tab:"Chase goal",label:"ATTACKING SHAPE",title:"1–3–1 · Chase a goal",mentality:"CONTROLLED ATTACK",note:"Create width and passing angles. The holding midfielder recovers immediately when possession is lost.",players:[
    {key:"gk",role:"GOALKEEPER",name:"Minti",duty:"Support the reset",x:50,y:91,className:"goalkeeper"},
    {key:"defender",role:"DEFENDER",name:"Chirag",duty:"Stay behind ball",x:50,y:73},
    {key:"holding",role:"HOLDING MID",name:"DJ",duty:"Recover back",x:50,y:54},
    {key:"leftWing",role:"LEFT WING",name:"Prajna / Sangram",duty:"Stretch play",x:24,y:35},
    {key:"rightWing",role:"RIGHT WING",name:"Varun",duty:"Attack far post",x:76,y:35},
    {key:"striker",role:"STRIKER",name:"Nuhu / Vivek",duty:"Link and finish",x:50,y:14}
  ]}
};
const roles=[
  {icon:"GK",title:"Goalkeeper / last player",players:"Minti · DJ · Shailesh",withBall:"Open an easy passing angle and choose the simple pass. Reset through the defense if the forward ball is risky.",transition:"Call who takes the ball and who covers the runner. Move early instead of reacting from the goal line.",defending:"Stay square, protect the center of the small goal, and communicate constantly with both defenders."},
  {icon:"DF",title:"Defender",players:"Chirag · DJ · Shailesh · Rajeev · Minti",withBall:"Spread wide enough to receive, look through midfield first, and advance only when the other defender stays back.",transition:"Recover goal-side immediately. The nearest defender slows the attack; the second defender covers behind.",defending:"Protect the center, show attackers outside, and never let both defenders chase the same player."},
  {icon:"CM",title:"CDM / defensive leader",players:"Chirag · Nuhu · DJ",withBall:"Offer a central passing option, switch the point of attack, and keep the team connected behind the ball.",transition:"Delay the counter and direct teammates. Track the first central runner before trying to win the ball.",defending:"Screen passes into the striker and decide when a defender should step forward or hold the line."},
  {icon:"MF",title:"Midfielder",players:"Prajna · Sangram",withBall:"Receive side-on, combine quickly, and support the forward without occupying the same space.",transition:"The closest midfielder presses. The other drops inside and protects the central passing lane.",defending:"Stay close enough to the defense to prevent gaps. Follow the ball across the pitch as a pair."},
  {icon:"FW",title:"Forward / winger",players:"Nuhu · Varun · Vivek",withBall:"Create width or run behind, combine with midfield, and attack the goal when the opposite winger has possession.",transition:"Press a poor touch, but remain available for the counter when the team needs an outlet.",defending:"Guide the opponent toward one side. Block the easy return pass instead of chasing the goalkeeper."},
  {icon:"MK",title:"Special marker",players:"DJ · Varun",withBall:"Release the mark when we have secure possession and become an immediate passing option.",transition:"Find the assigned threat first. Communicate any handoff clearly before moving to the ball.",defending:"Stay goal-side, match the run, and delay. The purpose is to reduce influence, not win every challenge."}
];
let currentOpponent="desi",currentShape="balanced";
function makeTabs(){const o=document.querySelector("#opponentTabs"),s=document.querySelector("#shapeTabs");Object.entries(opponents).forEach(([key,item])=>{const b=document.createElement("button");b.type="button";b.role="tab";b.textContent=item.label;b.dataset.key=key;b.addEventListener("click",()=>{currentOpponent=key;render()});o.append(b)});Object.entries(shapes).forEach(([key,item])=>{const b=document.createElement("button");b.type="button";b.role="tab";b.textContent=item.tab;b.dataset.key=key;b.addEventListener("click",()=>{currentShape=key;render()});s.append(b)})}
function renderPitch(shape,opponent){const pitch=document.querySelector("#pitch");pitch.innerHTML='<span class="halfway"></span><span class="top-box"></span>';shape.players.forEach(player=>{const node=document.createElement("div");node.className=`player-node ${player.className||""}`;node.style.left=`${player.x}%`;node.style.top=`${player.y}%`;const duty=currentShape==="balanced"&&opponent.duties[player.key];node.innerHTML=`<span>${player.role}</span><strong>${player.name}</strong><small>${duty||player.duty}</small>`;pitch.append(node)})}
function render(){const opponent=opponents[currentOpponent],shape=shapes[currentShape];document.querySelectorAll("#opponentTabs button").forEach(b=>{const a=b.dataset.key===currentOpponent;b.classList.toggle("active",a);b.setAttribute("aria-selected",a)});document.querySelectorAll("#shapeTabs button").forEach(b=>{const a=b.dataset.key===currentShape;b.classList.toggle("active",a);b.setAttribute("aria-selected",a)});document.querySelector("#shapeLabel").textContent=shape.label;document.querySelector("#shapeTitle").textContent=shape.title;document.querySelector("#mentality").textContent=shape.mentality;document.querySelector("#pitchFootnote").textContent=currentShape==="balanced"?opponent.footnote:shape.note;document.querySelector("#opponentName").textContent=opponent.label;document.querySelector("#opponentSummary").textContent=opponent.summary;document.querySelector("#threats").innerHTML=opponent.threats.map(n=>`<span>${n}</span>`).join("");document.querySelector("#instructions").innerHTML=opponent.instructions.map(i=>`<li>${i}</li>`).join("");document.querySelector("#markingPlan").textContent=opponent.marking;renderPitch(shape,opponent)}
function renderRoles(){document.querySelector("#roleGrid").innerHTML=roles.map(role=>`<article class="role-card"><header><span class="role-icon">${role.icon}</span><div><h3>${role.title}</h3><small>${role.players}</small></div></header><div class="role-moments"><div><b>WITH THE BALL</b><p>${role.withBall}</p></div><div><b>WHEN WE LOSE IT</b><p>${role.transition}</p></div><div><b>WITHOUT THE BALL</b><p>${role.defending}</p></div></div></article>`).join("")}
makeTabs();renderRoles();render();
